class ApplicationException(Exception):
    @property
    def message(self) -> str:
        return (
            self.args[0]
            if self.args
            else "An error has occurred in the application"
        )


# ValidationError
class ValidationError(ApplicationException): ...

class NotFoundError(ApplicationException): ...

class AlreadyExistsError(ApplicationException): ...

class InvalidPayloadError(ValidationError): ...

class InvalidCurrencyCodeError(ValidationError): ...

class InvalidCurrencyNameError(ValidationError): ...

class InvalidCurrencySignError(ValidationError): ...

class InvalidExchangeRateError(ValidationError): ...

class CurrencyNotFoundError(NotFoundError): ...

class CurrencyAlreadyExistsError(AlreadyExistsError): ...

class ExchangeRateAlreadyExistsError(AlreadyExistsError): ...

class InvalidCurrencyPairError(ValidationError): ...

class CurrencyPairNotFoundError(NotFoundError): ...

# db
class DatabaseError(ApplicationException): ...
